#!/bin/bash
export name=$(basename "$0")
PFX=$(dirname "$(which "$0")")    # dir in which the common code and tools reside
source "${PFX}"/common || {
  echo "${name}: could not source 'common' script, aborting..." ; exit 1
}
setup_env #-q

for IMG in $(ls ../meta*/recipes*/images/*.bb)
do
	printf "%-36s: %s\n" $(basename ${IMG}) $(dirname ${IMG})
	#echo "$(basename ${IMG})"
done

exit 0
