#!/bin/bash
# host_setup
# Setup an (Ubuntu) Linux host for Yocto Project (YP)
# (c) 2019 kaiwanTECH
# ref: https://www.yoctoproject.org/docs/latest/brief-yoctoprojectqs/brief-yoctoprojectqs.html
name=$(basename "$0")

#-------------- r u n c m d -------------------------------------------
# Display and run the provided command.
# Parameter 1 : the command to run
runcmd()
{
local DUMMY_RUN=0
local SEP="------------------------------"
[ $# -eq 0 ] && return
echo "${SEP}
$@"
[ ${DUMMY_RUN} -eq 1 ] && return
eval "$@"
}

get_hostpkg_up2date()
{
echo "
-----------------------------------------------------------------
Getting host packages up-to-date now ..."
runcmd "sudo apt update"
# ref: https://docs.yoctoproject.org/current/brief-yoctoprojectqs/index.html
runcmd "sudo apt install gawk wget git diffstat unzip texinfo gcc build-essential \
		chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils \
		iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 \
		xterm python3-subunit mesa-common-dev zstd liblz4-tool"
#runcmd "sudo apt-get install wget git-core diffstat unzip texinfo gcc-multilib \
#     build-essential socat cpio python python2.7 python3 python3-pip python3-pexpect \
#     xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev \
#     xterm g++ chrpath diffstat gawk zstd"
}

# We use the 'poky' distro as a base reference
# Parameters:
#  $1 : Yocto rel name
clone_yocto_poky()
{
[ $# -ne 1 ] && {
  echo "${name}:clone_yocto_poky() expects the Yocto release name as a parameter"
  exit 1
}
pwd
echo "
-----------------------------------------------------------------
Will now clone yocto into dir ${YOCTO_DIR}"
cd ${YOCTO_DIR} || exit 1
runcmd "git clone -b $1 https://git.yoctoproject.org/poky"
# TIP- if this doesn't work try substituting https:// with git:// (or vice-versa)
[ ! -d "${YOCTO_DIR}"/poky ] && {
  echo "${name}: the dir \"${YOCTO_DIR}/poky\" isn't there, something's gone wrong, aborting..."
  echo "TIP- try substituting https:// with git:// (or vice-versa)"
  exit 1
}
cd ${YOCTO_DIR}/poky || exit 1

echo "
${name}: We shall now show all the git tags and ask you to select one
 Press [Enter] to continue..."
read -r
git fetch --tags
echo "Pick a tag: (scroll through all and then type a tag name, eg. kirkstone)"
git tag
echo "Pick a tag: (now type a tag name, eg. kirkstone)

IMP TIP: usually, you should select the latest stable release (f.e. kirkstone / honister / ...)
(can find the release name here: https://www.yoctoproject.org/ )
Do NOT type the ver# after the name (i.e. just type 'kirkstone' for eg.)

"
read -r mytag

echo "git checkout -t origin/${mytag} -b my-${mytag}"
git checkout -t origin/${mytag} -b my-${mytag} || {
  echo "${name}: something's gone wrong, aborting..."
  exit 1
}
echo "The previous Git checkout command creates a local branch named my-${mytag}.
The files available to you in that branch exactly match the repository’s files in the ${mytag} release branch.
To keep it in sync simply do a 'git pull'
"
runcmd "git status"
}

project_specific_setup()
{
echo "
-----------------------------------------------------------------
Project-specific setup for Yocto:"
cd ${TOPDIR}/poky
# copy existing layers if any into the poky/<build-dir>/
#                     conf
#                     meta-prjlayer1
#                     meta-prjlayer2
#                       [...]
#                     meta-prjlayern

# next, adjust paths if required in <build-dir>/conf/bblayers.conf

# next, run
source oe-init-build-env
  # now in poky/<build-dir>/
bitbake-layers show-layers || exit 1
# and confirm all's ok

# Will perhaps need to clone some layers like, for example for the Raspberry Pi:
#  /opt/yocto/poky/meta-raspberrypi
#   ref: https://layers.openembedded.org/layerindex/branch/master/layer/meta-raspberrypi/
# under the poky/ folder
# Refer the 'meta raspberrypi documentation' PDF/site
#  http://meta-raspberrypi.readthedocs.io/en/latest/
# We keep this commented...
#cd ${TOPDIR}/poky
#git clone http://git.yoctoproject.org/meta-raspberrypi
}

# Perform the build
perform_build()
{
POKY_IMAGE_TO_BUILD=core-image-minimal    # or, core-image-full-cmdline
echo "
-----------------------------------------------------------------
${name}: Performing yocto bitbake build now
-----------------------------------------------------------------
bitbake ${POKY_IMAGE_TO_BUILD}
"
cd ${YOCTO_DIR}/poky
source oe-init-build-env
bitbake ${POKY_IMAGE_TO_BUILD}
}


### 'main' here

### Keep UPDATED !
# ref: https://www.yoctoproject.org/software-overview/downloads/
LATEST_YOCTO_RELNAME="langdale"
LATEST_YOCTO_RELVER="4.1"
###
[ $# -ne 2 ] && {
  echo "Usage: ${name} yocto-dir yocto-release-name-to-clone"
  echo "This script requires two parameters"
  echo "1. yocto-dir : to create and populate with the Yocto project (it shouldn't already exist)"
  echo "2. yocto-release-name-to-clone : check latest (or whichever one you want) on https://www.yoctoproject.org/software-overview/downloads/
   F.e. the latest (as of this script) is named '${LATEST_YOCTO_RELNAME}' ver $LATEST_YOCTO_RELVER)
   For this param, just specify the release name."

  exit 1
}
[ -d $1 ] && {
  echo "${name}: the dir specified \"$1\" already exists, won't overwrite, aborting.."
  exit 1
}

echo -n "
A quick check:
This helper script has the latest Yocto release as:
${LATEST_YOCTO_RELNAME} ver ${LATEST_YOCTO_RELVER}

Is this correct? [y/n] "
read re
if [ "${re}" != "y" -a "${re}" != "Y" ]; then
	echo "Ok, aborting. Pl update it in the script and rerun, thanks!"
	exit 1
fi

YOCTO_DIR=$(realpath $1)
YOCTO_RELNAME=$2
echo "YOCTO_DIR = ${YOCTO_DIR} . Yocto release specified: ${YOCTO_RELNAME}"
mkdir -p ${YOCTO_DIR} || exit 1

TOPDIR=$(pwd)
get_hostpkg_up2date

cd ${YOCTO_DIR} || exit 1
#pwd
echo "
-----------------------------------------------------------------
${name}: Yocto setup 1
-----------------------------------------------------------------
We're now ready to clone the yocto project onto your dir \"${YOCTO_DIR}\" ...
Press [Enter] to proceed, ^C to abort ..."
read
clone_yocto_poky ${YOCTO_RELNAME}

# If required, uncomment the below project_specific_setup() func and verify the
# code to perform prj-specific setup
#project_specific_setup

echo "
-----------------------------------------------------------------
${name}: Yocto setup 2
-----------------------------------------------------------------
Now, go to the yocto location
 ${YOCTO_DIR}/poky
run this:
 source oe-init-build-env [builddir-name]

Then edit and configure 
 ${YOCTO_DIR}/poky/build/conf/local.conf

Change the varable MACHINE to, for example:
 MACHINE ?= \"qemuarm64\"
save the file, and then proceed with the build.
"

# If required, uncomment the below func to build
#perform_build

exit 0
