#!/bin/bash
# burn4rpi
# A very simple wrapper over dd, for the common case of burning the (micro)
# SDcard image generated by Yocto for the Raspberry Pi.
# (c) Kaiwan N Billimoria, kaiwanTECH
# License: MIT
#
# F.e:
# ./burn4rpi.sh /opt/yocto/poky/build_rpi/tmp/deploy/images/raspberrypi3-64/core-image-base-raspberrypi3-64.rpi-sdimg
#
name=$(basename $0)
ofdisk=mmcblk0

[ $# -ne 1 ] && {
  echo "Usage: ${name} {path-to-rpi-sdimg-file}"
  exit 1
}
[ ! -f $1 ] && {
  echo "${name}: specified file \"$1\" doesn't exist (or lacking perms?) Aborting..."
  exit 1
}

lsblk | grep -q "${ofdisk}" || {
  echo "${name}: lsblk failed to find output disk \"${ofdisk}\" ? Aborting..."
  exit 1
}

cmd="sudo umount /dev/${ofdisk}* 2>/dev/null; sync"
eval "${cmd}"

IMG=${1}
cmd="sudo dd if=${IMG} of=/dev/${ofdisk} bs=4M"
echo "
${cmd}
"
echo "Please CAREFULLY VERIFY that this command is OK to run,
ESPECIALLY the 'of' device !!!

Press [Enter] to continue, ^C to abort ..." ; read -r
eval "${cmd}"
echo "done, sync-ing now..."
sync
