#!/bin/bash
name=$(basename $0)
source ./common || {
  echo "${name}: warning: could not source 'common'..." #; exit 1
  YOCTO_PFX=..   # assuming you're in the build dir
}

(
cd ${YOCTO_PFX}
for IMG in $(ls meta*/recipes*/images/*.bb)
do
	echo "$(basename ${IMG})"
done
)

